---
title: "Descarga y organización de datos de delitos (Policía Nacional)"
output: html_notebook
---

# Fuentes de Datos - Proyecto Delitos en Colombia

Este proyecto utiliza las bases de datos públicas de la **Policía Nacional de Colombia**.\
Los archivos no se incluyen directamente en este repositorio, solo se listan los enlaces oficiales.

------------------------------------------------------------------------

### ABIGEATO

-   [Abigeato 2024 (Hurto a cabezas de ganado)](https://www.policia.gov.co/sites/default/files/delitos-impacto/Hurto%20a%20cabezas%20de%20ganado2024_0.xlsx)
-   [Abigeato 2023 (](https://www.policia.gov.co/sites/default/files/delitos-impacto/hurto%20cabezas%20de%20ganado.._0.xlsx)[Hurto a cabezas de ganado](https://www.policia.gov.co/sites/default/files/delitos-impacto/Hurto%20a%20cabezas%20de%20ganado2024_0.xlsx)[)](https://www.policia.gov.co/sites/default/files/delitos-impacto/hurto%20cabezas%20de%20ganado.._0.xlsx)
-   [Abigeato 2022 (](https://www.policia.gov.co/sites/default/files/delitos-impacto/abigeato.xls_2.xlsx)[Hurto a cabezas de ganado](https://www.policia.gov.co/sites/default/files/delitos-impacto/Hurto%20a%20cabezas%20de%20ganado2024_0.xlsx)[)](https://www.policia.gov.co/sites/default/files/delitos-impacto/abigeato.xls_2.xlsx)
-   [Abigeato 2021 (](https://www.policia.gov.co/sites/default/files/delitos-impacto/abigeato_6.xls)[Hurto a cabezas de ganado](https://www.policia.gov.co/sites/default/files/delitos-impacto/Hurto%20a%20cabezas%20de%20ganado2024_0.xlsx)[)](https://www.policia.gov.co/sites/default/files/delitos-impacto/abigeato_6.xls)
-   [Abigeato](https://www.policia.gov.co/sites/default/files/delitos-impacto/abigeato_2020.xls)[2020 (](https://www.policia.gov.co/sites/default/files/delitos-impacto/abigeato_6.xls)[Hurto a cabezas de ganado](https://www.policia.gov.co/sites/default/files/delitos-impacto/Hurto%20a%20cabezas%20de%20ganado2024_0.xlsx)[)](https://www.policia.gov.co/sites/default/files/delitos-impacto/abigeato_6.xls)
-   [Abigeato 2019](https://www.policia.gov.co/sites/default/files/delitos-impacto/abigeato_2019_3.xlsx)[(](https://www.policia.gov.co/sites/default/files/delitos-impacto/abigeato_6.xls)[Hurto a cabezas de ganado](https://www.policia.gov.co/sites/default/files/delitos-impacto/Hurto%20a%20cabezas%20de%20ganado2024_0.xlsx)[)](https://www.policia.gov.co/sites/default/files/delitos-impacto/abigeato_6.xls)
-   [Abigeato 2018](https://www.policia.gov.co/sites/default/files/delitos-impacto/abigeato_2018_2.xlsx)[(](https://www.policia.gov.co/sites/default/files/delitos-impacto/abigeato_6.xls)[Hurto a cabezas de ganado](https://www.policia.gov.co/sites/default/files/delitos-impacto/Hurto%20a%20cabezas%20de%20ganado2024_0.xlsx)[)](https://www.policia.gov.co/sites/default/files/delitos-impacto/abigeato_6.xls)

------------------------------------------------------------------------

### AMENAZAS

-   [Amenazas 2024](https://www.policia.gov.co/sites/default/files/delitos-impacto/Amenazas2024_0.xlsx)
-   [Amenazas 2023](https://www.policia.gov.co/sites/default/files/delitos-impacto/amenzas..xlsx)
-   [Amenazas 2022](https://www.policia.gov.co/sites/default/files/delitos-impacto/amenazas_13.xls)
-   [Amenazas 2021](https://www.policia.gov.co/sites/default/files/delitos-impacto/amenazas_11.xls)
-   [Amenazas 2020](https://www.policia.gov.co/sites/default/files/delitos-impacto/amenazas_2020.xlsx)
-   [Amenazas 2019](https://www.policia.gov.co/sites/default/files/delitos-impacto/amenazas_2019_1.xlsx)
-   [Amenazas 2018](https://www.policia.gov.co/sites/default/files/delitos-impacto/amenazas_2018_1.xlsx)

------------------------------------------------------------------------

### DELITOS SEXUALES

-   [Delitos sexuales 2024](https://www.policia.gov.co/sites/default/files/delitos-impacto/Delitos%20sexuales2024_0.xlsx)
-   [Delitos sexuales 2023](https://www.policia.gov.co/sites/default/files/delitos-impacto/delitos%20sexuales.xlsx)
-   [Delitos sexuales 2022](https://www.policia.gov.co/sites/default/files/delitos-impacto/delitos_sexuales_11.xls)
-   [Delitos sexuales 2021](https://www.policia.gov.co/sites/default/files/delitos-impacto/delitos_sexuales_9.xls)
-   [Delitos sexuales 2020](https://www.policia.gov.co/sites/default/files/delitos-impacto/delitos_sexuales_2020.xls)
-   [Delitos sexuales 2019](https://www.policia.gov.co/sites/default/files/delitos-impacto/delitos_sexuales_2019_0.xlsx)
-   [Delitos sexuales 2018](https://www.policia.gov.co/sites/default/files/delitos-impacto/delitos_sexuales_2018_0.xlsx)

------------------------------------------------------------------------

### EXTORSIÓN

-   [Extorsión 2024](https://www.policia.gov.co/sites/default/files/delitos-impacto/Extorsión2024_0.xlsx)
-   [Extorsión 2023](https://www.policia.gov.co/sites/default/files/delitos-impacto/extorsion_11.xlsx)
-   [Extorsión 2022](https://www.policia.gov.co/sites/default/files/delitos-impacto/extorsion_11.xls)
-   [Extorsión 2021](https://www.policia.gov.co/sites/default/files/delitos-impacto/extorsion_9.xls)
-   [Extorsión 2020](https://www.policia.gov.co/sites/default/files/delitos-impacto/extorsion_2020_1.xls)
-   [Extorsión 2019](https://www.policia.gov.co/sites/default/files/delitos-impacto/extorsion_2019_2.xlsx)
-   [Extorsión 2018](https://www.policia.gov.co/sites/default/files/delitos-impacto/extorsion_2018_3.xlsx)

------------------------------------------------------------------------

### HOMICIDIOS

-   [Homicidio 2024](https://www.policia.gov.co/sites/default/files/delitos-impacto/Homicidio%20Intencional2024_0.xlsx)
-   [Homicidio 2023](https://www.policia.gov.co/sites/default/files/delitos-impacto/homicidio%20intencional_0.xlsx)
-   [Homicidio 2022](https://www.policia.gov.co/sites/default/files/delitos-impacto/Homicidio%20Intencional%202022.xlsx)
-   [Homicidio 2021](https://www.policia.gov.co/sites/default/files/delitos-impacto/Homicidio%20Intencional%202021.xlsx)
-   [Homicidio 2020](https://www.policia.gov.co/sites/default/files/delitos-impacto/Homicidio%20Intencional%202020.xlsx)
-   [Homicidio 2019](https://www.policia.gov.co/sites/default/files/delitos-impacto/Homicidio%20Intencional%202019.xlsx)
-   [Homicidio 2018](https://www.policia.gov.co/sites/default/files/delitos-impacto/Homicidio%20Intencional%202018.xlsx)

------------------------------------------------------------------------

### HOMICIDIOS EN ACCIDENTES DE TRÁNSITO

-   [Homicidios en accidente de tránsito 2024](https://www.policia.gov.co/sites/default/files/delitos-impacto/Homicidios%20en%20accidente%20de%20tr%C3%A1nsito2024_0.xlsx)
-   [Homicidios en accidente de tránsito 2023](https://www.policia.gov.co/sites/default/files/delitos-impacto/homicidios%20en%20accidente%20de%20transito....xlsx)
-   [Homicidios en accidentes de tránsito 2022](https://www.policia.gov.co/sites/default/files/delitos-impacto/homicidios_en_accidente_de_transito_11.xls)
-   [Homicidios en accidentes de tránsito 2021](https://www.policia.gov.co/sites/default/files/delitos-impacto/homicidios_en_accidente_de_transito_9.xls)
-   [Homicidios en accidente de tránsito 2020](https://www.policia.gov.co/sites/default/files/delitos-impacto/homicidios_accidente_de_transito_2020_2.xls)
-   [Homicidios en accidente de tránsito 2019](https://www.policia.gov.co/sites/default/files/delitos-impacto/homicidios_en_accidente_de_transito_2019.xlsx)
-   [Homicidios en accidente de tránsito 2018](https://www.policia.gov.co/sites/default/files/delitos-impacto/homicidios_en_accidente_de_transito_2018_1.xlsx)

------------------------------------------------------------------------

### HURTO A PERSONAS

-   [Hurto a personas 2024](https://www.policia.gov.co/sites/default/files/delitos-impacto/Hurto%20a%20personas2024_0.xlsx)
-   [Hurto a personas 2023](https://www.policia.gov.co/sites/default/files/delitos-impacto/hurto%20a%20personas.xlsx)
-   [Hurto a personas 2022](https://www.policia.gov.co/sites/default/files/delitos-impacto/hurto_a_personas_17.xlsx)
-   [Hurto a personas 2021](https://www.policia.gov.co/sites/default/files/delitos-impacto/hurto_a_personas_9.xlsx)
-   [Hurto a personas 2020](https://www.policia.gov.co/sites/default/files/delitos-impacto/hurto_personas_2020_0.xlsx)
-   [Hurto a personas 2019](https://www.policia.gov.co/sites/default/files/delitos-impacto/hurto_a_personas_2019_0.xlsx)
-   [Hurto a personas 2018](https://www.policia.gov.co/sites/default/files/delitos-impacto/hurto_a_personas_2018_1.xlsx)

------------------------------------------------------------------------

### HURTO A RESIDENCIAS

-   [Hurto a residencias 2024](https://www.policia.gov.co/sites/default/files/delitos-impacto/Hurto%20a%20residencias2024_0.xlsx)
-   [Hurto a residencias 2023](https://www.policia.gov.co/sites/default/files/delitos-impacto/hurto%20a%20residencias....xlsx)
-   [Hurto a residencias 2022](https://www.policia.gov.co/sites/default/files/delitos-impacto/hurto_a_residencias_4.xls)
-   [Hurto a residencias 2021](https://www.policia.gov.co/sites/default/files/delitos-impacto/hurto_a_residencias_5.xlsx)
-   [Hurto a residencias 2020](https://www.policia.gov.co/sites/default/files/delitos-impacto/hurto_residencias_2020.xls)
-   [Hurto a residencias 2019](https://www.policia.gov.co/sites/default/files/delitos-impacto/hurto_a_residencias_2019_0.xlsx)
-   [Hurto a residencias 2018](https://www.policia.gov.co/sites/default/files/delitos-impacto/hurto_a_residencias_2018_1.xlsx)

------------------------------------------------------------------------

### HURTO DE AUTOMOTORES 

-   [Hurto de automotores 2024](https://www.policia.gov.co/sites/default/files/delitos-impacto/Hurto%20automotores2024_0.xlsx)
-   [Hurto de automotores 2023](https://www.policia.gov.co/sites/default/files/delitos-impacto/hurto%20automotores....xlsx)
-   [Hurto de automotores 2022](https://www.policia.gov.co/sites/default/files/delitos-impacto/hurto_automotores_4.xls)
-   [Hurto de automotores 2021](https://www.policia.gov.co/sites/default/files/delitos-impacto/hurto_automotores_5.xlsx)
-   [Hurto de automotores 2020](https://www.policia.gov.co/sites/default/files/delitos-impacto/hurto_automotores_2020_1.xls)
-   [Hurto de automotores 2019](https://www.policia.gov.co/sites/default/files/delitos-impacto/hurto_automotores_2019_0.xlsx)
-   [Hurto de automotores 2018 (variante 1)](https://www.policia.gov.co/sites/default/files/delitos-impacto/hurto_automotores_2018_1.xlsx)
-   [Hurto de automotores 2018 (variante 2)](https://www.policia.gov.co/sites/default/files/delitos-impacto/hurto_automotores_2018_2.xlsx)

------------------------------------------------------------------------

### HURTO DE MOTOCICLETAS 

-   [Hurto a motocicletas 2024](https://www.policia.gov.co/sites/default/files/delitos-impacto/Hurto%20a%20motocicletas2024_0.xlsx)
-   [Hurto a motocicletas 2023](https://www.policia.gov.co/sites/default/files/delitos-impacto/hurto%20a%20motocicletas....xlsx)
-   [Hurto a motocicletas 2022](https://www.policia.gov.co/sites/default/files/delitos-impacto/hurto_a_motocicletas_7.xls)
-   [Hurto a motocicletas 2021](https://www.policia.gov.co/sites/default/files/delitos-impacto/hurto_a_motocicletas_5.xls)
-   [Hurto a motocicletas 2020](https://www.policia.gov.co/sites/default/files/delitos-impacto/hurto_a_motocicletas_2020.xls)
-   [Hurto a motocicletas 2019](https://www.policia.gov.co/sites/default/files/delitos-impacto/hurto_motocicletas_2019_0.xlsx)
-   [Hurto a motocicletas 2018](https://www.policia.gov.co/sites/default/files/delitos-impacto/hurto_motocicletas_2018_0.xlsx)

------------------------------------------------------------------------

### HURTOS A ENTIDADES COMERCIALES 

-   [Hurto a comercio 2024](https://www.policia.gov.co/sites/default/files/delitos-impacto/Hurto%20a%20comercio2024_0.xlsx)
-   [Hurto a comercio 2023](https://www.policia.gov.co/sites/default/files/delitos-impacto/hurto%20a%20comercio..._0.xlsx)
-   [Hurto a comercio 2022](https://www.policia.gov.co/sites/default/files/delitos-impacto/hurto_a_comercio_11.xls)
-   [Hurto a comercio 2021](https://www.policia.gov.co/sites/default/files/delitos-impacto/hurto_a_comercio_9.xls)
-   [Hurto a comercio 2020](https://www.policia.gov.co/sites/default/files/delitos-impacto/hurto_a_comercio_2020.xls)
-   [Hurto a comercio 2019](https://www.policia.gov.co/sites/default/files/delitos-impacto/hurto_a_comercio_2019_0.xlsx)
-   [Hurto a comercio 2018](https://www.policia.gov.co/sites/default/files/delitos-impacto/hurto_a_comercio_2018_1.xlsx)

------------------------------------------------------------------------

### HURTOS A ENTIDADES FINANCIERAS 

-   [Hurto a entidades financieras 2024](https://www.policia.gov.co/sites/default/files/delitos-impacto/Hurto%20a%20entidades%20Financieras2024_0.xlsx)
-   [Hurto a entidades financieras 2023](https://www.policia.gov.co/sites/default/files/delitos-impacto/hurto%20entidades%20financieras.xlsx)
-   [Hurto a entidades financieras 2022](https://www.policia.gov.co/sites/default/files/delitos-impacto/hurto_entidades_financieras_11.xls)
-   [Hurto a entidades financieras 2021](https://www.policia.gov.co/sites/default/files/delitos-impacto/hurto_entidades_financieras_9.xls)
-   [Hurto a entidades financieras 2020](https://www.policia.gov.co/sites/default/files/delitos-impacto/hurto_entidades_financieras_2020.xls)
-   [Hurto a entidades financieras 2019](https://www.policia.gov.co/sites/default/files/delitos-impacto/hurto_a_entidades_financieras_2019_3.xlsx)
-   [Hurto a entidades financieras 2018 (variante 2)](https://www.policia.gov.co/sites/default/files/delitos-impacto/hurto_a_entidades_financieras_2018_0.xlsx)
-   [Hurto a entidades financieras 2018 (variante 1)](https://www.policia.gov.co/sites/default/files/delitos-impacto/hurto_a_entidades_financieras_2018_3.xlsx)

------------------------------------------------------------------------

### LESIONES EN ACCIDENTES DE TRÁNSITO 

-   [Lesiones en accidente de tránsito 2024](https://www.policia.gov.co/sites/default/files/delitos-impacto/Lesiones%20en%20accidente%20de%20tr%C3%A1nsito2024_2.xlsx)
-   [Lesiones en accidente de tránsito 2023](https://www.policia.gov.co/sites/default/files/delitos-impacto/lesiones%20en%20accidente%20de%20transito....xlsx)
-   [Lesiones en accidente de tránsito 2022](https://www.policia.gov.co/sites/default/files/delitos-impacto/lesiones_en_accidente_de_transito_7.xlsx)
-   [Lesiones en accidente de tránsito 2021](https://www.policia.gov.co/sites/default/files/delitos-impacto/lesiones_en_accidente_de_transito_5.xls)
-   [Lesiones en accidente de tránsito 2020](https://www.policia.gov.co/sites/default/files/delitos-impacto/lesiones_en_accidente_de_transito_2020_1.xls)
-   [Lesiones en accidente de tránsito 2019](https://www.policia.gov.co/sites/default/files/delitos-impacto/lesiones_en_accidente_de_transito_2019_0.xlsx)
-   [Lesiones en accidente de tránsito 2018 (variante 2)](https://www.policia.gov.co/sites/default/files/delitos-impacto/lesiones_en_accidente_de_transito_2018_1.xlsx)
-   [Lesiones en accidente de tránsito 2018 (variante 1)](https://www.policia.gov.co/sites/default/files/delitos-impacto/lesiones_en_accidente_de_transito_2018_0.xlsx)

------------------------------------------------------------------------

### LESIONES PERSONALES 

-   [Lesiones personales 2024](https://www.policia.gov.co/sites/default/files/delitos-impacto/Lesiones%20personales2024_0.xlsx)
-   [Lesiones personales 2023](https://www.policia.gov.co/sites/default/files/delitos-impacto/lesiones%20personales..._0.xlsx)
-   [Lesiones personales 2022](https://www.policia.gov.co/sites/default/files/delitos-impacto/lesiones_personales_0.xlsx)
-   [Lesiones personales 2021](https://www.policia.gov.co/sites/default/files/delitos-impacto/lesiones_personales_5.xls)
-   [Lesiones personales 2020](https://www.policia.gov.co/sites/default/files/delitos-impacto/lesiones_personales_2020.xlsx)
-   [Lesiones personales 2019](https://www.policia.gov.co/sites/default/files/delitos-impacto/lesiones_personales_2019_0.xlsx)
-   [Lesiones personales 2018](https://www.policia.gov.co/sites/default/files/delitos-impacto/lesiones_personales_2018_0.xlsx)

------------------------------------------------------------------------

### PIRATERÍA TERRESTRE 

-   [Piratería terrestre 2024](https://www.policia.gov.co/sites/default/files/delitos-impacto/Hurto%20pirater%C3%ADa%20terrestre2024_0.xlsx)
-   [Piratería terrestre 2023](https://www.policia.gov.co/sites/default/files/delitos-impacto/hurto%20pirateria%20terrestre_1.xlsx)
-   [Piratería terrestre 2022](https://www.policia.gov.co/sites/default/files/delitos-impacto/hurto_a_pirateria_terrestre_11.xls)
-   [Piratería terrestre 2021](https://www.policia.gov.co/sites/default/files/delitos-impacto/hurto_a_pirateria_terrestre_9.xls)
-   [Piratería terrestre 2020](https://www.policia.gov.co/sites/default/files/delitos-impacto/pirateria_terrestre_2020_1.xls)
-   [Piratería terrestre 2019](https://www.policia.gov.co/sites/default/files/delitos-impacto/pirateria_terrestre_2019_3.xlsx)
-   [Piratería terrestre 2018 (variante 2)](https://www.policia.gov.co/sites/default/files/delitos-impacto/pirateria_terrestre_2018_2.xlsx)
-   [Piratería terrestre 2018 (variante 1)](https://www.policia.gov.co/sites/default/files/delitos-impacto/pirateria_terrestre_2018_1.xlsx)

------------------------------------------------------------------------

### SECUESTRO 

-   [Secuestro 2024](https://www.policia.gov.co/sites/default/files/delitos-impacto/Secuestro2024_0.xlsx)
-   [Secuestro 2023](https://www.policia.gov.co/sites/default/files/delitos-impacto/secuestro..._0.xlsx)
-   [Secuestro 2022](https://www.policia.gov.co/sites/default/files/delitos-impacto/secuestro_11.xls)
-   [Secuestro 2021](https://www.policia.gov.co/sites/default/files/delitos-impacto/secuestro_9.xls)
-   [Secuestro 2020](https://www.policia.gov.co/sites/default/files/delitos-impacto/secuestro_2020.xls)
-   [Secuestro 2019](https://www.policia.gov.co/sites/default/files/delitos-impacto/secuestro_2019_3.xlsx)
-   [Secuestro 2018 (variante 2)](https://www.policia.gov.co/sites/default/files/delitos-impacto/secuestro_2018_3.xlsx)
-   [Secuestro 2018 (variante 1)](https://www.policia.gov.co/sites/default/files/delitos-impacto/secuestro_2018_2.xlsx)

------------------------------------------------------------------------

### TERRORISMO 

-   [Terrorismo 2024](https://www.policia.gov.co/sites/default/files/delitos-impacto/Terrorismo2024_0.xlsx)
-   [Terrorismo 2023](https://www.policia.gov.co/sites/default/files/delitos-impacto/terrorismo_4.xlsx)
-   [Terrorismo 2022](https://www.policia.gov.co/sites/default/files/delitos-impacto/terrorismo_11.xls)
-   [Terrorismo 2021](https://www.policia.gov.co/sites/default/files/delitos-impacto/terrorismo_9.xls)
-   [Terrorismo 2020 (variante 2)](https://www.policia.gov.co/sites/default/files/delitos-impacto/terrorismo_2020_1.xls)
-   [Terrorismo 2020 (variante 1)](https://www.policia.gov.co/sites/default/files/delitos-impacto/terrorismo_2020_0.xls)
-   [Terrorismo 2019](https://www.policia.gov.co/sites/default/files/delitos-impacto/terrorismo_2019_2.xlsx)
-   [Terrorismo 2018 (variante 2)](https://www.policia.gov.co/sites/default/files/delitos-impacto/terrorismo_2018_2.xlsx)
-   [Terrorismo 2018 (variante 1)](https://www.policia.gov.co/sites/default/files/delitos-impacto/terrorismo_2018_0.xlsx)

------------------------------------------------------------------------

### VIOLENCIA INTRAFAMILIAR 

-   [Violencia intrafamiliar 2024](https://www.policia.gov.co/sites/default/files/delitos-impacto/Violencia%20intrafamiliar2024_0.xlsx)
-   [Violencia intrafamiliar 2023](https://www.policia.gov.co/sites/default/files/delitos-impacto/violencia%20intrafamiliar....xlsx)
-   [Violencia intrafamiliar 2022](https://www.policia.gov.co/sites/default/files/delitos-impacto/violencia_intrafamiliar_12.xls)
-   [Violencia intrafamiliar 2021](https://www.policia.gov.co/sites/default/files/delitos-impacto/violencia_intrafamiliar_10.xls)
-   [Violencia intrafamiliar 2020](https://www.policia.gov.co/sites/default/files/delitos-impacto/violencia_intrafamiliar_2020.xls_0.xlsx)
-   [Violencia intrafamiliar 2019](https://www.policia.gov.co/sites/default/files/delitos-impacto/violencia_intrafamiliar_2019_0.xlsx)
-   [Violencia intrafamiliar 2018 (variante 2)](https://www.policia.gov.co/sites/default/files/delitos-impacto/violencia_intrafamiliar_2018_1.xlsx)
-   [Violencia intrafamiliar 2018 (variante 1)](https://www.policia.gov.co/sites/default/files/delitos-impacto/violencia_intrafamiliar_2018_0.xlsx)
